# comments
name: Maven_Build_Example
env:
  JAVA_VERSION : "17"
  DISTRIBUTION : "zulu"
on: 
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Step 1 - Checkout master branchfrom Github
      uses: actions/checkout@v4
    
    - name: Step 2 - Set up JDK 17
    - uses: actions/setup-java@v4
      with:
        distribution: "${{env.DISTRIBUTION}}" 
        java-version: "${{env.JAVA_VERSION}}"     
