# comments
name: TicTacToe
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flack-deploy-ver-${{ github.sha }}"
on: 
  push:
    branches:
      - master

jobs: 
  my_test:
    runs-on: ubuntu-latest

    steps: 
    - name: print Hello Message
      run : echo "Heelo World from Test"

    - name: Execute few commands
      run : |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name is ${{ env.APPLICATION_NAME}}"
        
    - name: List current folder
      run: ls -la 

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder
      run: ls -la 
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
    env: 
      VAR1: "This is Job Level Variable1"
      VAR2: "This is Job Level Variable2"

    steps: 
    - name: print Hello Message
      run : echo "Hello World from Test"

    - name: print Deployment package 
      run : echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"

    - name: print Deployment package 
      run : |
        echo "Var1 = ${{env.VAR1}}"
        echo "Var2 = ${{env.VAR2}}"
        echo "Var3 = $LOCAL_VAR"
      env: 
        LOCAL_VAR: "This is super local Environment variable"
      
    - name: lets test some packages if they are here 2
      run : aws --version

    - name: lets test some packages if they are here 1
      run : zip
